[[segment]]
parsername = "text"
refreshinterval = "1s"
template = "{{ . }}"

[[segment]]
parsername = "processes"
refreshinterval = "1s"
template = """
 chrome
 firefox
 rsync
 zoom
V vpn
󰎁 mpv
 sxiv
 gimp
"""

[[segment]]
parsername = "bluetooth"
refreshinterval = "1m"
template = """
 {{ if .IsServiceActive }}
{{ if .IsControllerPowered }}󰂯{{ else }}󰂲{{ end }}
{{ if .DeviceType | eq "audio-headset" }}{{ end }}
{{ if .DeviceType | eq "audio-card" }}󰓃{{ end }}
{{ end }}
"""

[[segment]]
parsername = "audio"
refreshinterval = "1m"
template = """
 {{ if .OutAvailable }}
{{ if .OutMuted }}󰖁{{ else }}{{ end }}{{ .OutVolume }}%
{{ end }}
{{ if .InAvailable }}
{{ if .InMuted }}{{ else }}󰍬{{ end }}{{ .InVolume }}%
{{ end }}
"""


[[segment]]
parsername = "cpu"
refreshinterval = "1s"
#template = """{{ .FreqGHz | printf "%4.1f" }}GHz {{ .Load | printf "%4.1f" }}%"""
template = """{{ .FreqGHz | printf "%4.1f" }}GHz {{ .Load | printf "%4.1f" }}% {{ .Load | bar }}"""
# https://github.com/maicher/kmstatus/blob/master/internal/hardware/cpu/data.go

[[segment]]
parsername = "temperature"
refreshinterval = "5s"
template = """{{ if .Name | eq "k10temp" }}
 {{ .Value }}°
{{ end }}"""

# In Celsius:
# template = " {{ .Name }}:{{ .Celsius }}°C"

# In Fahrenheit:
# template = " {{ .Name }}:{{ .Fahrenheit }}°F"

# Do not display all available temperatures, but a specific one:
# template = """ {{ if .Name | eq "test" }}
# {{ .Value }}°
# {{ end }}"""

# Specific two:
# template = """ {{ if (.Name | eq "test1") | or (.Name | eq "test2") }}
# {{ .Value }}°
# {{ end }}"""
# https://github.com/maicher/kmstatus/blob/master/internal/hardware/temperature/data.go

[[segment]]
parsername = "mem"
refreshinterval = "1s"
template = """
 {{ .Used | human 0 }}/{{ .Total | human 0 }}({{ .UsedPercentage | printf "%.1f" }}%)
{{ if .SwapUsed | gt 0 }}
 Swap: {{ .SwapUsed | human 0 }}/{{ .SwapTotal | human 0 }} ({{ .SwapUsedPercentage | printf "%.1f"}}%)
{{ end }}
"""

[[segment]]
parsername = "network"
refreshinterval = "1s"
template = """
{{ if .Name | hasPrefix "en" }}
 [{{ .Name }} {{ .Rx | human 0 | ljust 4 }}{{ .Tx | human 0 | ljust 4 }}]
{{ end }}
"""

[[segment]]
parsername = "clock"
template = """ {{ . | format "2006-01-02 15:04:05" }}"""
