[[segment]]
parsername = "cpu"
parseinterval = "1s"
parseonsig = false
#template = """{{ .FreqGHz | printf "%4.1f" }}GHz {{ .Load | printf "%4.1f" }}%"""
template = """{{ .FreqGHz | printf "%4.1f" }}GHz {{ .Load | printf "%4.1f" }}% {{ .Load | bar }}"""
# https://github.com/maicher/kmst/blob/master/internal/hardware/cpu/data.go

[[segment]]
parsername = "temperature"
parseinterval = "5s"
parseonsig = false
template = """{{ if .Name | eq "k10temp" }}
 {{ .Value }}°
{{ end }}"""

# In Celsius:
# template = " {{ .Name }}:{{ .Celsius }}°C"

# In Fahrenheit:
# template = " {{ .Name }}:{{ .Fahrenheit }}°F"

# Do not display all available temperatures, but a specific one:
# template = """ {{ if .Name | eq "test" }}
# {{ .Value }}°
# {{ end }}"""

# Specific two:
# template = """ {{ if (.Name | eq "test1") | or (.Name | eq "test2") }}
# {{ .Value }}°
# {{ end }}"""
# https://github.com/maicher/kmst/blob/master/internal/hardware/temperature/data.go

[[segment]]
parsername = "mem"
parseinterval = "1s"
parseonsig = false
template = """
 {{ .Used | human 0 }}/{{ .Total | human 0 }}({{ .UsedPercentage | printf "%.1f" }}%)
{{ if .SwapUsed | gt 0 }}
 Swap: {{ .SwapUsed | human 0 }}/{{ .SwapTotal | human 0 }} ({{ .SwapUsedPercentage | printf "%.1f"}}%)
{{ end }}
"""

[[segment]]
parsername = "network"
parseinterval = "1s"
parseonsig = false
template = """
{{ if .Name | hasPrefix "en" }}
 [{{ .Name }} {{ .Rx | human 0 | ljust 4 }}{{ .Tx | human 0 | ljust 4 }}]
{{ end }}
"""

[[segment]]
parsername = "clock"
template = """ {{ . | format "2006-01-02 15:04:05" }}"""
